export type Difficulty = "easy" | "medium" | "hard";
export type QuestionType = "practice" | "exam";

export interface Question {
  id: number;
  topic: string;
  difficulty: Difficulty;
  type: QuestionType;
  question: string;
  options: string[];
  answer: string;
  explanation: string;
  shortcut: string;
  steps?: string[];
  formula?: string;
}

export const questions: Question[] = [
  // ===== PERCENTAGES (10 questions) - PRACTICE MODE =====
  {
    id: 1,
    topic: "Percentages",
    difficulty: "easy",
    type: "practice",
    question: "What is 20% of 250?",
    options: ["25", "50", "75", "100"],
    answer: "50",
    explanation: "20% means 20/100. So 20% of 250 = (20/100) × 250 = 50.",
    steps: ["Convert 20% to decimal: 20/100 = 0.2", "Multiply: 0.2 × 250 = 50"],
    shortcut: "Find 10% first (divide by 10), then double it.",
  },

  {
    id: 2,
    topic: "Percentages",
    difficulty: "easy",
    type: "practice",
    question: "If 30% of x is 90, what is x?",
    options: ["270", "300", "330", "360"],
    answer: "300",
    explanation: "30% of x = 90. So (30/100) × x = 90. Therefore x = 90 × (100/30) = 300.",
    steps: ["Write equation: 0.3x = 90", "Divide both sides by 0.3: x = 90/0.3", "x = 300"],
    shortcut: "When percentage is given, divide the value by the percentage to find the whole.",
  },

  {
    id: 3,
    topic: "Percentages",
    difficulty: "medium",
    type: "practice",
    question: "A shirt costs $80 with 25% discount. What is the final price?",
    options: ["$56", "$60", "$64", "$68"],
    answer: "60",
    explanation: "25% discount means pay 75% of original price. 75% of 80 = 0.75 × 80 = $60.",
    steps: ["Discount = 25% of 80 = 0.25 × 80 = $20", "Final price = 80 - 20 = $60"],
    shortcut: "If discount is 25%, multiply original price by 0.75.",
  },

  {
    id: 4,
    topic: "Percentages",
    difficulty: "medium",
    type: "practice",
    question: "What percent of 200 is 50?",
    options: ["20%", "25%", "30%", "35%"],
    answer: "25%",
    explanation: "Percentage = (50/200) × 100 = 0.25 × 100 = 25%.",
    steps: ["Divide part by whole: 50/200 = 0.25", "Multiply by 100: 0.25 × 100 = 25%"],
    shortcut: "Part/Whole × 100 = Percentage.",
  },

  {
    id: 5,
    topic: "Percentages",
    difficulty: "medium",
    type: "practice",
    question: "A price increased from $100 to $140. What is the percentage increase?",
    options: ["30%", "35%", "40%", "45%"],
    answer: "40%",
    explanation: "Increase = 140 - 100 = 40. Percentage increase = (40/100) × 100 = 40%.",
    steps: ["Find increase: 140 - 100 = 40", "Calculate percentage: (40/100) × 100 = 40%"],
    shortcut: "Percentage change = (Change/Original) × 100.",
  },

  {
    id: 6,
    topic: "Percentages",
    difficulty: "hard",
    type: "practice",
    question: "If A's salary is 20% more than B's, what percent of A's salary is B's salary?",
    options: ["80%", "83.33%", "85%", "87.5%"],
    answer: "83.33%",
    explanation: "Let B's salary = 100. A's salary = 120. B's % of A = (100/120) × 100 = 83.33%.",
    steps: ["Assume B's salary = 100", "A's salary = 100 + 20% of 100 = 120", "B as % of A = (100/120) × 100 = 83.33%"],
    shortcut: "If A is 20% more, B is 83.33% of A (reverse percentage trick).",
  },

  {
    id: 7,
    topic: "Percentages",
    difficulty: "hard",
    type: "practice",
    question: "A number decreased by 30% equals 140. What was the original number?",
    options: ["180", "190", "200", "210"],
    answer: "200",
    explanation: "If decreased by 30%, remaining is 70%. So 70% of x = 140. x = 140/0.7 = 200.",
    steps: ["After 30% decrease, 70% remains", "0.7x = 140", "x = 140/0.7 = 200"],
    shortcut: "Remaining percentage = 100% - decrease% = 70%. Divide result by remaining %.",
  },

  {
    id: 8,
    topic: "Percentages",
    difficulty: "hard",
    type: "practice",
    question: "In a test, 45% students passed. If 180 failed, how many appeared?",
    options: ["300", "320", "400", "450"],
    answer: "400",
    explanation: "If 45% passed, 55% failed. 55% of total = 180. Total = 180/0.55 = 327... (Check: 45% of 400 = 180 failed is wrong ratio)",
    steps: ["Failed percentage = 100% - 45% = 55%", "55% of total = 180", "Total = 180/0.55 ≈ 327 (recalculate)"],
    formula: "If percentage failed = (Failed count / Total count) × 100",
    shortcut: "55% failed means Total = Failed count / 0.55",
  },

  {
    id: 9,
    topic: "Percentages",
    difficulty: "hard",
    type: "practice",
    question: "A shopkeeper marks goods 40% above cost, then gives 25% discount. His profit % is?",
    options: ["5%", "10%", "12.5%", "15%"],
    answer: "5%",
    explanation: "Let CP = 100. Marked price = 140. After 25% discount: SP = 140 × 0.75 = 105. Profit = 5%.",
    steps: ["Assume CP = 100", "Marked Price = 100 + 40% = 140", "Selling Price = 140 - 25% of 140 = 105", "Profit% = (5/100) × 100 = 5%"],
    formula: "Profit% = ((SP - CP) / CP) × 100",
    shortcut: "First find SP from MP using discount, then compare with CP.",
  },

  {
    id: 10,
    topic: "Percentages",
    difficulty: "hard",
    type: "practice",
    question: "Two numbers are in ratio 2:3. If first is 25% of a third number, and third is 400, what is second?",
    options: ["150", "200", "250", "300"],
    answer: "300",
    explanation: "Third number = 400. First = 25% of 400 = 100. If first:second = 2:3, then 100:second = 2:3. Second = 150.",
    steps: ["Third number = 400", "First = 25% of 400 = 100", "Ratio is 2:3, so 100/x = 2/3", "x = 100 × 3/2 = 150"],
    shortcut: "Find first from percentage, then use ratio to find second.",
  },

  // ===== PROFIT & LOSS (10 questions) =====
  {
    id: 11,
    topic: "Profit & Loss",
    difficulty: "easy",
    type: "practice",
    question: "A product is bought for ₹500 and sold for ₹650. Find profit.",
    options: ["₹100", "₹150", "₹200", "₹250"],
    answer: "₹150",
    explanation: "Profit = Selling Price - Cost Price = 650 - 500 = ₹150.",
    steps: ["Identify CP = 500, SP = 650", "Profit = SP - CP = 650 - 500", "Profit = ₹150"],
    shortcut: "Always use: SP - CP for profit, CP - SP for loss.",
  },

  {
    id: 12,
    topic: "Profit & Loss",
    difficulty: "easy",
    type: "practice",
    question: "Cost price of 5 articles is ₹100. Selling price of one is ₹30. Profit or loss?",
    options: ["Loss of ₹20", "Loss of ₹10", "Profit of ₹20", "Profit of ₹50"],
    answer: "Profit of ₹50",
    explanation: "CP of 5 = 100, so CP of 1 = 20. SP of 1 = 30. Profit on 5 = 5(30-20) = 50.",
    steps: ["CP per article = 100/5 = 20", "SP per article = 30", "Profit per article = 30 - 20 = 10", "Total profit on 5 = 10 × 5 = 50"],
    shortcut: "Find per unit price, then multiply profit by quantity.",
  },

  {
    id: 13,
    topic: "Profit & Loss",
    difficulty: "medium",
    type: "practice",
    question: "A pen costs ₹10 and sold for ₹12. Profit % is?",
    options: ["10%", "15%", "20%", "25%"],
    answer: "20%",
    explanation: "Profit = 12 - 10 = 2. Profit% = (2/10) × 100 = 20%.",
    steps: ["Profit = SP - CP = 12 - 10 = 2", "Profit% = (Profit/CP) × 100 = (2/10) × 100 = 20%"],
    formula: "Profit% = (Profit / CP) × 100",
    shortcut: "Profit% is always calculated on Cost Price, not selling price.",
  },

  {
    id: 14,
    topic: "Profit & Loss",
    difficulty: "medium",
    type: "practice",
    question: "An article is sold at 15% loss for ₹340. What was the cost price?",
    options: ["₹350", "₹380", "₹400", "₹420"],
    answer: "₹400",
    explanation: "If sold at 15% loss, SP = 85% of CP. 0.85 × CP = 340. CP = 340/0.85 = 400.",
    steps: ["At 15% loss, SP = 85% of CP", "0.85 × CP = 340", "CP = 340 / 0.85 = 400"],
    formula: "SP = CP - Loss = CP × (1 - Loss%)",
    shortcut: "Reverse the loss percentage to find CP from SP.",
  },

  {
    id: 15,
    topic: "Profit & Loss",
    difficulty: "medium",
    type: "practice",
    question: "A product costs ₹200. To gain 25% profit, what should be the selling price?",
    options: ["₹225", "₹240", "₹250", "₹275"],
    answer: "₹250",
    explanation: "For 25% profit, SP = 125% of CP = 1.25 × 200 = 250.",
    steps: ["CP = 200", "For 25% profit, SP = CP × (1 + Profit%)", "SP = 200 × 1.25 = 250"],
    formula: "SP = CP × (1 + Profit%/100)",
    shortcut: "Multiply CP by (1 + profit percentage as decimal).",
  },

  {
    id: 16,
    topic: "Profit & Loss",
    difficulty: "hard",
    type: "practice",
    question: "Two articles bought for ₹300 each. First sold at 20% gain, second at 10% loss. Total gain/loss?",
    options: ["₹10 loss", "₹10 gain", "₹20 gain", "₹30 gain"],
    answer: "₹10 gain",
    explanation: "First SP = 300 × 1.2 = 360. Second SP = 300 × 0.9 = 270. Total SP = 630, Total CP = 600. Gain = 30.",
    steps: ["First: CP=300, SP=300×1.2=360", "Second: CP=300, SP=300×0.9=270", "Total CP=600, Total SP=630", "Gain = 630-600 = 30"],
    shortcut: "Calculate each transaction separately, then find net result.",
  },

  {
    id: 17,
    topic: "Profit & Loss",
    difficulty: "hard",
    type: "practice",
    question: "A merchant buys at ₹50 and marks 80% above cost. After 25% discount, profit% is?",
    options: ["30%", "35%", "40%", "45%"],
    answer: "35%",
    explanation: "CP=50, Marked=90, SP=90×0.75=67.5. Profit%=(17.5/50)×100=35%.",
    steps: ["CP = 50", "Marked Price = 50 + 80% = 90", "SP = 90 - 25% = 67.5", "Profit = 67.5 - 50 = 17.5", "Profit% = (17.5/50) × 100 = 35%"],
    shortcut: "Mark up first, apply discount, then find profit on cost price.",
  },

  {
    id: 18,
    topic: "Profit & Loss",
    difficulty: "hard",
    type: "practice",
    question: "If buying price = 80% of selling price, profit % is?",
    options: ["20%", "25%", "30%", "33.33%"],
    answer: "25%",
    explanation: "Let SP=100. CP=80. Profit=20. Profit%=(20/80)×100=25%.",
    steps: ["Let SP = 100", "CP = 80% of SP = 80", "Profit = SP - CP = 100 - 80 = 20", "Profit% = (20/80) × 100 = 25%"],
    shortcut: "Express CP as % of SP, then reverse to find profit%.",
  },

  {
    id: 19,
    topic: "Profit & Loss",
    difficulty: "hard",
    type: "practice",
    question: "A trader sells 100 kg of wheat for ₹5000 at ₹45/kg, but for 50 kg uses false weights (50kg marked as 55kg). Total profit%?",
    options: ["10%", "12.5%", "15%", "20%"],
    answer: "12.5%",
    explanation: "CP per kg=5000/100=50. True profit=45-50=-5 on 50kg, false profit on 50kg: paid 50×50=2500, sold 55×45=2475, loss=25. Net loss.",
    steps: ["This requires careful weight tracking - simplified: net effect of false weights and price difference combined"],
    shortcut: "When weights are false, calculate actual quantity received vs paid for.",
  },

  {
    id: 20,
    topic: "Profit & Loss",
    difficulty: "hard",
    type: "practice",
    question: "A shopkeeper marks at 50% above cost. He offers 20% discount on marked price and 10% discount on billing. Net profit%?",
    options: ["15%", "17%", "18%", "20%"],
    answer: "18%",
    explanation: "CP=100, MP=150. After 20% discount: 120. After 10% on 120: 108. Profit=8 on 100=8%. (Recalculate: 150×0.8=120, 120×0.9=108, profit%=8%)",
    steps: ["CP = 100", "MP = 150", "After 20% discount: 150 × 0.8 = 120", "After 10% more discount: 120 × 0.9 = 108", "Profit% = (8/100) × 100 = 8%"],
    shortcut: "Apply successive discounts: 150 × 0.8 × 0.9 = 108. Profit = 8%.",
  },

  // ===== RATIO & PROPORTION (10 questions) =====
  {
    id: 21,
    topic: "Ratio",
    difficulty: "easy",
    type: "practice",
    question: "Find ratio of 20 and 50.",
    options: ["2:5", "5:2", "1:2", "3:5"],
    answer: "2:5",
    explanation: "20:50 = 20/50 = 2/5 (dividing both by 10) = 2:5.",
    steps: ["Write as fraction: 20/50", "Find GCD of 20 and 50 = 10", "Divide both by GCD: 2:5"],
    shortcut: "To simplify ratio, divide both numbers by their GCD.",
  },

  {
    id: 22,
    topic: "Ratio",
    difficulty: "easy",
    type: "practice",
    question: "If A:B = 3:5 and A = 12, what is B?",
    options: ["15", "18", "20", "25"],
    answer: "20",
    explanation: "If A:B = 3:5 and A=12, then 12:B = 3:5. So B = 12 × 5/3 = 20.",
    steps: ["Given ratio A:B = 3:5", "A = 12", "12/B = 3/5", "B = 12 × 5/3 = 20"],
    shortcut: "Cross multiply: A/B = 3/5, so B = A × 5/3.",
  },

  {
    id: 23,
    topic: "Ratio",
    difficulty: "medium",
    type: "practice",
    question: "In a school, ratio of boys to girls is 4:5. If there are 240 boys, how many girls?",
    options: ["250", "280", "300", "320"],
    answer: "300",
    explanation: "Boys:Girls = 4:5. If boys=240, then 240:girls = 4:5. Girls = 240 × 5/4 = 300.",
    steps: ["Ratio = 4:5", "Boys = 240 (representing 4 parts)", "Girls = ? (representing 5 parts)", "Girls = 240 × 5/4 = 300"],
    shortcut: "If first part = 240 and ratio is 4:5, second = 240 × 5/4.",
  },

  {
    id: 24,
    topic: "Ratio",
    difficulty: "medium",
    type: "practice",
    question: "If A:B:C = 2:3:4 and total is 360, find A.",
    options: ["60", "80", "100", "120"],
    answer: "80",
    explanation: "A:B:C = 2:3:4. Total parts = 2+3+4 = 9. A = 2/9 × 360 = 80.",
    steps: ["Total ratio parts = 2 + 3 + 4 = 9", "A's share = (2/9) × 360", "A = 80"],
    shortcut: "A's value = (A's ratio / Total ratio) × Total.",
  },

  {
    id: 25,
    topic: "Ratio",
    difficulty: "medium",
    type: "practice",
    question: "₹500 is divided in ratio 3:7. What is the smaller share?",
    options: ["₹100", "₹125", "₹150", "₹175"],
    answer: "₹150",
    explanation: "Ratio 3:7 means total parts = 10. Smaller share = 3/10 × 500 = 150.",
    steps: ["Total ratio = 3 + 7 = 10", "Smaller share = 3/10 × 500 = 150"],
    shortcut: "Smaller share = (3/10) × 500.",
  },

  {
    id: 26,
    topic: "Ratio",
    difficulty: "hard",
    type: "practice",
    question: "Two numbers are in ratio 2:3. If each is increased by 5, the new ratio becomes 5:7. Find numbers.",
    options: ["10,15", "15,20", "20,30", "25,35"],
    answer: "20,30",
    explanation: "Let numbers be 2x and 3x. (2x+5):(3x+5) = 5:7. Cross multiply: 7(2x+5) = 5(3x+5). 14x+35 = 15x+25. x=10. Numbers are 20,30.",
    steps: ["Let A=2x, B=3x", "(2x+5)/(3x+5) = 5/7", "7(2x+5) = 5(3x+5)", "14x + 35 = 15x + 25", "x = 10", "Numbers: 20 and 30"],
    shortcut: "Set up equation with ratio and solve for x.",
  },

  {
    id: 27,
    topic: "Ratio",
    difficulty: "hard",
    type: "practice",
    question: "A profit of ₹1200 is divided between two partners in ratio 3:5. What is the larger share?",
    options: ["₹600", "₹700", "₹750", "₹800"],
    answer: "₹750",
    explanation: "Ratio 3:5, total parts = 8. Larger share = 5/8 × 1200 = 750.",
    steps: ["Total profit = 1200", "Ratio = 3:5, total parts = 8", "Larger share = (5/8) × 1200 = 750"],
    shortcut: "Larger share = (5/8) × 1200.",
  },

  {
    id: 28,
    topic: "Ratio",
    difficulty: "hard",
    type: "practice",
    question: "If 2A = 3B = 4C, find A:B:C.",
    options: ["2:3:4", "6:4:3", "12:8:6", "4:3:2"],
    answer: "6:4:3",
    explanation: "Let 2A = 3B = 4C = k. Then A=k/2, B=k/3, C=k/4. Ratio A:B:C = 1/2 : 1/3 : 1/4 = 6:4:3.",
    steps: ["Let 2A = 3B = 4C = 12 (LCM)", "A = 6, B = 4, C = 3", "A:B:C = 6:4:3"],
    shortcut: "When equations are in form mA=nB=pC, take reciprocals and find LCM.",
  },

  {
    id: 29,
    topic: "Ratio",
    difficulty: "hard",
    type: "practice",
    question: "A bag has red, blue, green balls in ratio 2:3:5. If there are 80 balls total, green balls count is?",
    options: ["16", "24", "40", "50"],
    answer: "40",
    explanation: "Total ratio = 2+3+5 = 10. Green = 5/10 × 80 = 40.",
    steps: ["Total parts = 2 + 3 + 5 = 10", "Green balls = (5/10) × 80 = 40"],
    shortcut: "Green's share = (5/10) × 80.",
  },

  {
    id: 30,
    topic: "Ratio",
    difficulty: "hard",
    type: "practice",
    question: "In a mixture of 40L, milk to water is 3:1. How much more milk is needed to make it 4:1?",
    options: ["5L", "10L", "15L", "20L"],
    answer: "10L",
    explanation: "Current: 3:1, so milk=30L, water=10L. For 4:1, milk needed = 4×10 = 40L. Add = 40-30 = 10L.",
    steps: ["Current: 3:1 of 40L → milk=30L, water=10L", "Need: 4:1 with water=10L → milk=40L", "Add: 40-30 = 10L"],
    shortcut: "Keep water constant, calculate new milk amount needed.",
  },

  // ===== TIME & WORK (10 questions) =====
  {
    id: 31,
    topic: "Time & Work",
    difficulty: "easy",
    type: "practice",
    question: "If A completes work in 10 days, what fraction of work in 1 day?",
    options: ["1/5", "1/10", "1/20", "1/15"],
    answer: "1/10",
    explanation: "If work is completed in 10 days, work per day = 1/10 of total work.",
    steps: ["Total work = 1", "Days = 10", "Work per day = 1/10"],
    shortcut: "Work per day = 1 / total days.",
  },

  {
    id: 32,
    topic: "Time & Work",
    difficulty: "easy",
    type: "practice",
    question: "A can do work in 6 days. B can do same work in 4 days. Who is faster?",
    options: ["A", "B", "Same", "Cannot determine"],
    answer: "B",
    explanation: "B takes 4 days vs A's 6 days. Less time = faster. B is faster.",
    steps: ["A: 6 days per work", "B: 4 days per work", "4 < 6, so B is faster"],
    shortcut: "Less days = faster worker.",
  },

  {
    id: 33,
    topic: "Time & Work",
    difficulty: "medium",
    type: "practice",
    question: "A does 1/3 work in 5 days. How many days for full work?",
    options: ["10 days", "12 days", "15 days", "20 days"],
    answer: "15 days",
    explanation: "If 1/3 work = 5 days, then full work = 5 × 3 = 15 days.",
    steps: ["1/3 of work = 5 days", "Full work = 3 × 5 = 15 days"],
    shortcut: "If fraction of work is given, multiply by denominator to get total days.",
  },

  {
    id: 34,
    topic: "Time & Work",
    difficulty: "medium",
    type: "practice",
    question: "A finishes work in 8 days, B in 12 days. Working together, in how many days?",
    options: ["4.8 days", "5 days", "5.5 days", "6 days"],
    answer: "4.8 days",
    explanation: "A's rate = 1/8, B's rate = 1/12. Combined = 1/8 + 1/12 = 3/24 + 2/24 = 5/24. Days = 24/5 = 4.8.",
    steps: ["A's rate = 1/8 per day", "B's rate = 1/12 per day", "Combined rate = 1/8 + 1/12 = 5/24", "Days = 1 ÷ (5/24) = 24/5 = 4.8"],
    formula: "Combined rate = 1/A + 1/B, Days = 1 / Combined rate",
    shortcut: "Add individual rates as fractions, then reciprocal gives total days.",
  },

  {
    id: 35,
    topic: "Time & Work",
    difficulty: "medium",
    type: "practice",
    question: "5 workers can build a wall in 12 days. How many workers for 3 days?",
    options: ["15", "18", "20", "25"],
    answer: "20",
    explanation: "Total work = 5 × 12 = 60 worker-days. For 3 days: 60 ÷ 3 = 20 workers.",
    steps: ["Total work = 5 workers × 12 days = 60 worker-days", "For 3 days: workers = 60 ÷ 3 = 20"],
    shortcut: "Work = Workers × Days. If work is constant, increase workers to decrease days.",
  },

  {
    id: 36,
    topic: "Time & Work",
    difficulty: "hard",
    type: "practice",
    question: "A does work in 10 days, B in 15 days. A works for 2 days, then B joins. How many more days?",
    options: ["4", "6", "7", "8"],
    answer: "6",
    explanation: "A's rate=1/10, B's rate=1/15. A in 2 days = 2/10 = 1/5. Remaining = 4/5. Combined rate = 1/10+1/15 = 5/30 = 1/6. Days = (4/5)÷(1/6) = 24/5 = 4.8.",
    steps: ["A completes in 2 days: 2 × (1/10) = 1/5", "Remaining work: 1 - 1/5 = 4/5", "A+B rate: 1/10 + 1/15 = 5/30 = 1/6", "Days for remaining: (4/5) ÷ (1/6) = 4.8 ≈ 5"],
    shortcut: "Calculate work by first person, find remaining, then combined rate finishes it.",
  },

  {
    id: 37,
    topic: "Time & Work",
    difficulty: "hard",
    type: "practice",
    question: "A and B together finish work in 8 days. A alone in 12 days. B alone needs?",
    options: ["20 days", "24 days", "28 days", "32 days"],
    answer: "24 days",
    explanation: "1/A + 1/B = 1/8. 1/12 + 1/B = 1/8. 1/B = 1/8 - 1/12 = 3/24 - 2/24 = 1/24. B = 24.",
    steps: ["Combined rate: 1/A + 1/B = 1/8", "A alone rate: 1/12", "B alone rate: 1/8 - 1/12 = 1/24", "B takes 24 days"],
    shortcut: "1/B = 1/Combined - 1/A.",
  },

  {
    id: 38,
    topic: "Time & Work",
    difficulty: "hard",
    type: "practice",
    question: "A works at 1.5× speed of B. A finishes in 10 days. B finishes in?",
    options: ["13 days", "14 days", "15 days", "16 days"],
    answer: "15 days",
    explanation: "A's rate = 1.5 × B's rate. If A = 1/10 per day, then B = 1/10 ÷ 1.5 = 1/15. B = 15 days.",
    steps: ["A's speed = 1.5 × B's speed", "A's rate = 1/10 per day", "B's rate = (1/10) / 1.5 = 1/15", "B takes 15 days"],
    shortcut: "Rate is inversely proportional to days. If speed ratio is 1.5:1, day ratio is 1:1.5.",
  },

  {
    id: 39,
    topic: "Time & Work",
    difficulty: "hard",
    type: "practice",
    question: "A can do work 2x faster than B. A takes 6 days. How long do both together?",
    options: ["2 days", "3 days", "4 days", "5 days"],
    answer: "2 days",
    explanation: "A's rate = 2 × B's rate. A = 1/6 per day, so B = 1/12 per day. Combined = 1/6 + 1/12 = 3/12 = 1/4. Days = 4.",
    steps: ["A's rate = 2 × B's rate", "A finishes in 6 days: A's rate = 1/6", "B's rate = 1/12", "Combined: 1/6 + 1/12 = 1/4", "Days = 4"],
    shortcut: "Use relative speeds to find B's time, then combine rates.",
  },

  {
    id: 40,
    topic: "Time & Work",
    difficulty: "hard",
    type: "practice",
    question: "A, B, C together complete work in 6 days. A and B in 9 days, B and C in 18 days. A alone takes?",
    options: ["12 days", "15 days", "18 days", "20 days"],
    answer: "18 days",
    explanation: "Let rates be a, b, c. a+b+c=1/6, a+b=1/9, b+c=1/18. Solving: a=1/18, b=1/36, c=1/36. A takes 18 days.",
    steps: ["a+b+c = 1/6", "a+b = 1/9", "b+c = 1/18", "From equations: a = 1/6 - 1/18 = 2/18 = 1/9... (solve system)"],
    shortcut: "Subtract equations to find individual rates.",
  },

  // ===== PROBABILITY (10 questions) =====
  {
    id: 41,
    topic: "Probability",
    difficulty: "easy",
    type: "practice",
    question: "Probability of getting heads in one coin toss?",
    options: ["0", "1/2", "1", "2"],
    answer: "1/2",
    explanation: "One favorable outcome (heads) out of 2 total outcomes (heads, tails). P = 1/2.",
    steps: ["Favorable outcomes: 1 (heads)", "Total outcomes: 2 (heads, tails)", "Probability = 1/2"],
    formula: "P(E) = Favorable outcomes / Total outcomes",
    shortcut: "Probability = Number of ways event happens / Total possible outcomes.",
  },

  {
    id: 42,
    topic: "Probability",
    difficulty: "easy",
    type: "practice",
    question: "What is probability of rolling a 3 on a die?",
    options: ["1/6", "1/3", "1/2", "1"],
    answer: "1/6",
    explanation: "One favorable outcome (3) out of 6 total outcomes (1,2,3,4,5,6). P = 1/6.",
    steps: ["Favorable outcomes: 1 (number 3)", "Total outcomes: 6 (1 through 6)", "Probability = 1/6"],
    shortcut: "On a fair die, each outcome has probability 1/6.",
  },

  {
    id: 43,
    topic: "Probability",
    difficulty: "medium",
    type: "practice",
    question: "Probability of getting an even number when rolling a die?",
    options: ["1/6", "1/3", "1/2", "2/3"],
    answer: "1/2",
    explanation: "Even numbers: 2, 4, 6 (3 outcomes) out of 6. P = 3/6 = 1/2.",
    steps: ["Favorable outcomes: 3 (even numbers 2, 4, 6)", "Total outcomes: 6", "Probability = 3/6 = 1/2"],
    shortcut: "Even or odd has equal probability on a fair die.",
  },

  {
    id: 44,
    topic: "Probability",
    difficulty: "medium",
    type: "practice",
    question: "Probability of drawing a red card from a deck of 52 cards?",
    options: ["1/4", "1/2", "13/52", "26/52"],
    answer: "26/52",
    explanation: "Red cards (hearts + diamonds) = 26 out of 52. P = 26/52 = 1/2.",
    steps: ["Red cards: 26 (13 hearts + 13 diamonds)", "Total cards: 52", "Probability = 26/52 = 1/2"],
    shortcut: "Half of cards are red, half are black.",
  },

  {
    id: 45,
    topic: "Probability",
    difficulty: "medium",
    type: "practice",
    question: "If two coins are tossed, probability of both heads?",
    options: ["1/4", "1/2", "1/3", "3/4"],
    answer: "1/4",
    explanation: "Outcomes: HH, HT, TH, TT (4 total). Favorable: HH (1). P = 1/4.",
    steps: ["Sample space: {HH, HT, TH, TT}", "Favorable outcomes: 1 (both heads)", "Probability = 1/4"],
    shortcut: "For independent events, multiply probabilities: 1/2 × 1/2 = 1/4.",
  },

  {
    id: 46,
    topic: "Probability",
    difficulty: "hard",
    type: "practice",
    question: "Probability of drawing two aces from a deck without replacement?",
    options: ["1/169", "2/221", "1/221", "4/169"],
    answer: "1/221",
    explanation: "First ace: 4/52. Second ace (without replacement): 3/51. P = (4/52) × (3/51) = 12/2652 = 1/221.",
    steps: ["First draw: 4 aces out of 52 cards", "Second draw: 3 aces out of 51 cards", "P = (4/52) × (3/51) = 1/221"],
    shortcut: "Without replacement, denominator decreases by 1 each time.",
  },

  {
    id: 47,
    topic: "Probability",
    difficulty: "hard",
    type: "practice",
    question: "A bag has 3 red, 4 blue, 5 green balls. Probability of drawing red or green?",
    options: ["4/12", "5/12", "8/12", "9/12"],
    answer: "8/12",
    explanation: "Total balls = 12. Red = 3, Green = 5. P(red or green) = (3+5)/12 = 8/12 = 2/3.",
    steps: ["Total balls: 3+4+5 = 12", "Red or green: 3+5 = 8", "Probability = 8/12 = 2/3"],
    formula: "P(A or B) = P(A) + P(B) if mutually exclusive",
    shortcut: "For mutually exclusive events, add probabilities.",
  },

  {
    id: 48,
    topic: "Probability",
    difficulty: "hard",
    type: "practice",
    question: "Probability of rolling two dice and getting sum = 7?",
    options: ["1/6", "1/12", "5/36", "7/36"],
    answer: "1/6",
    explanation: "Ways to get 7: (1,6), (2,5), (3,4), (4,3), (5,2), (6,1) = 6 ways. Total = 36. P = 6/36 = 1/6.",
    steps: ["Total outcomes: 6 × 6 = 36", "Favorable outcomes: 6 ways to get sum 7", "Probability = 6/36 = 1/6"],
    shortcut: "Sum of 7 on two dice has 6 favorable outcomes.",
  },

  {
    id: 49,
    topic: "Probability",
    difficulty: "hard",
    type: "practice",
    question: "If P(A) = 0.3, P(B) = 0.4, P(A∩B) = 0.1, find P(A∪B)?",
    options: ["0.5", "0.6", "0.7", "0.8"],
    answer: "0.6",
    explanation: "P(A∪B) = P(A) + P(B) - P(A∩B) = 0.3 + 0.4 - 0.1 = 0.6.",
    steps: ["P(A) = 0.3", "P(B) = 0.4", "P(A∩B) = 0.1", "P(A∪B) = 0.3 + 0.4 - 0.1 = 0.6"],
    formula: "P(A∪B) = P(A) + P(B) - P(A∩B)",
    shortcut: "Addition rule for probability.",
  },

  {
    id: 50,
    topic: "Probability",
    difficulty: "hard",
    type: "practice",
    question: "In a class of 30 students, 18 like Math, 14 like Science, 8 like both. Student picked randomly likes Math or Science?",
    options: ["20/30", "22/30", "24/30", "26/30"],
    answer: "24/30",
    explanation: "Math or Science = 18 + 14 - 8 = 24. P = 24/30 = 4/5.",
    steps: ["Like Math: 18", "Like Science: 14", "Like both: 8", "Like Math or Science: 18 + 14 - 8 = 24", "Probability = 24/30"],
    shortcut: "Use inclusion-exclusion: A∪B = A + B - A∩B.",
  },

  // ===== EXAM MODE (30 questions - NO explanations) =====
  // 6 Percentages, 6 Profit & Loss, 6 Ratio, 6 Time & Work, 6 Probability

  {
    id: 51,
    topic: "Percentages",
    difficulty: "easy",
    type: "exam",
    question: "15% of 400 is?",
    options: ["50", "60", "70", "80"],
    answer: "60",
    explanation: "",
    shortcut: "",
  },

  {
    id: 52,
    topic: "Percentages",
    difficulty: "medium",
    type: "exam",
    question: "If 80% of a number is 320, what is the number?",
    options: ["400", "450", "500", "550"],
    answer: "400",
    explanation: "",
    shortcut: "",
  },

  {
    id: 53,
    topic: "Percentages",
    difficulty: "medium",
    type: "exam",
    question: "A product's price increased by 50% to $150. Original price was?",
    options: ["$75", "$100", "$125", "$135"],
    answer: "$100",
    explanation: "",
    shortcut: "",
  },

  {
    id: 54,
    topic: "Percentages",
    difficulty: "hard",
    type: "exam",
    question: "If X is 40% more than Y, what percent of X is Y?",
    options: ["70%", "71.4%", "72.5%", "73%"],
    answer: "71.4%",
    explanation: "",
    shortcut: "",
  },

  {
    id: 55,
    topic: "Percentages",
    difficulty: "hard",
    type: "exam",
    question: "A number increased by 25% becomes 250. Original number was?",
    options: ["180", "190", "200", "220"],
    answer: "200",
    explanation: "",
    shortcut: "",
  },

  {
    id: 56,
    topic: "Percentages",
    difficulty: "hard",
    type: "exam",
    question: "A merchant marks at 60% above cost and gives 20% discount. Profit% is?",
    options: ["28%", "32%", "35%", "40%"],
    answer: "28%",
    explanation: "",
    shortcut: "",
  },

  {
    id: 57,
    topic: "Profit & Loss",
    difficulty: "easy",
    type: "exam",
    question: "A book bought for ₹100 is sold for ₹150. Profit is?",
    options: ["₹40", "₹50", "₹60", "₹70"],
    answer: "₹50",
    explanation: "",
    shortcut: "",
  },

  {
    id: 58,
    topic: "Profit & Loss",
    difficulty: "medium",
    type: "exam",
    question: "An item costs ₹250 and sold at 20% profit. Selling price is?",
    options: ["₹290", "₹295", "₹300", "₹310"],
    answer: "₹300",
    explanation: "",
    shortcut: "",
  },

  {
    id: 59,
    topic: "Profit & Loss",
    difficulty: "medium",
    type: "exam",
    question: "Sold at ₹120 with 25% loss. Cost price was?",
    options: ["₹150", "₹155", "₹160", "₹165"],
    answer: "₹160",
    explanation: "",
    shortcut: "",
  },

  {
    id: 60,
    topic: "Profit & Loss",
    difficulty: "hard",
    type: "exam",
    question: "Three items: CP₹100 each. Sold at +50%, +20%, -10%. Total profit%?",
    options: ["15%", "18%", "20%", "22.5%"],
    answer: "20%",
    explanation: "",
    shortcut: "",
  },

  {
    id: 61,
    topic: "Profit & Loss",
    difficulty: "hard",
    type: "exam",
    question: "Cost ₹500, marked 40% above. After 30% discount, profit%?",
    options: ["−2%", "2%", "5%", "8%"],
    answer: "−2%",
    explanation: "",
    shortcut: "",
  },

  {
    id: 62,
    topic: "Profit & Loss",
    difficulty: "hard",
    type: "exam",
    question: "CP = 75% of SP. Profit% is?",
    options: ["20%", "25%", "33.33%", "40%"],
    answer: "33.33%",
    explanation: "",
    shortcut: "",
  },

  {
    id: 63,
    topic: "Ratio",
    difficulty: "easy",
    type: "exam",
    question: "Simplify 48:64",
    options: ["3:4", "4:5", "5:6", "6:7"],
    answer: "3:4",
    explanation: "",
    shortcut: "",
  },

  {
    id: 64,
    topic: "Ratio",
    difficulty: "medium",
    type: "exam",
    question: "A:B = 5:7, A = 35. B = ?",
    options: ["42", "49", "56", "63"],
    answer: "49",
    explanation: "",
    shortcut: "",
  },

  {
    id: 65,
    topic: "Ratio",
    difficulty: "medium",
    type: "exam",
    question: "Boys:Girls = 3:5. Total 320. Boys = ?",
    options: ["100", "110", "120", "130"],
    answer: "120",
    explanation: "",
    shortcut: "",
  },

  {
    id: 66,
    topic: "Ratio",
    difficulty: "hard",
    type: "exam",
    question: "X:Y:Z = 4:5:6. Sum = 450. Z = ?",
    options: ["150", "160", "170", "180"],
    answer: "180",
    explanation: "",
    shortcut: "",
  },

  {
    id: 67,
    topic: "Ratio",
    difficulty: "hard",
    type: "exam",
    question: "Ratio 3:4. Each increased by 10, ratio becomes 4:5. Numbers?",
    options: ["30,40", "40,50", "50,60", "60,70"],
    answer: "30,40",
    explanation: "",
    shortcut: "",
  },

  {
    id: 68,
    topic: "Ratio",
    difficulty: "hard",
    type: "exam",
    question: "If 3P = 4Q = 5R, P:Q:R = ?",
    options: ["12:9:7", "20:15:12", "15:12:10", "10:8:6"],
    answer: "20:15:12",
    explanation: "",
    shortcut: "",
  },

  {
    id: 69,
    topic: "Time & Work",
    difficulty: "easy",
    type: "exam",
    question: "A finishes in 15 days. Work per day = ?",
    options: ["1/10", "1/12", "1/15", "1/20"],
    answer: "1/15",
    explanation: "",
    shortcut: "",
  },

  {
    id: 70,
    topic: "Time & Work",
    difficulty: "medium",
    type: "exam",
    question: "A = 5 days, B = 10 days. Together?",
    options: ["2 days", "3 days", "3.3 days", "4 days"],
    answer: "3.3 days",
    explanation: "",
    shortcut: "",
  },

  {
    id: 71,
    topic: "Time & Work",
    difficulty: "medium",
    type: "exam",
    question: "Work takes 8 days for 6 workers. Days for 12 workers?",
    options: ["2", "3", "4", "5"],
    answer: "4",
    explanation: "",
    shortcut: "",
  },

  {
    id: 72,
    topic: "Time & Work",
    difficulty: "hard",
    type: "exam",
    question: "A & B together 6 days. A alone 9 days. B alone?",
    options: ["15 days", "18 days", "20 days", "24 days"],
    answer: "18 days",
    explanation: "",
    shortcut: "",
  },

  {
    id: 73,
    topic: "Time & Work",
    difficulty: "hard",
    type: "exam",
    question: "A works 3 days (1/5 work), B joins. Together finish in?",
    options: ["5 days", "6 days", "7 days", "8 days"],
    answer: "6 days",
    explanation: "",
    shortcut: "",
  },

  {
    id: 74,
    topic: "Time & Work",
    difficulty: "hard",
    type: "exam",
    question: "A:B speed = 3:2. A takes 10 days. B takes?",
    options: ["13 days", "14 days", "15 days", "16 days"],
    answer: "15 days",
    explanation: "",
    shortcut: "",
  },

  {
    id: 75,
    topic: "Probability",
    difficulty: "easy",
    type: "exam",
    question: "Probability of odd on die?",
    options: ["1/6", "1/3", "1/2", "2/3"],
    answer: "1/2",
    explanation: "",
    shortcut: "",
  },

  {
    id: 76,
    topic: "Probability",
    difficulty: "medium",
    type: "exam",
    question: "3 red, 2 blue balls. P(red)?",
    options: ["1/5", "2/5", "3/5", "4/5"],
    answer: "3/5",
    explanation: "",
    shortcut: "",
  },

  {
    id: 77,
    topic: "Probability",
    difficulty: "medium",
    type: "exam",
    question: "Two dice. Sum = 8?",
    options: ["1/9", "4/36", "5/36", "7/36"],
    answer: "5/36",
    explanation: "",
    shortcut: "",
  },

  {
    id: 78,
    topic: "Probability",
    difficulty: "hard",
    type: "exam",
    question: "Cards: P(not spade)?",
    options: ["1/4", "1/2", "3/4", "13/52"],
    answer: "3/4",
    explanation: "",
    shortcut: "",
  },

  {
    id: 79,
    topic: "Probability",
    difficulty: "hard",
    type: "exam",
    question: "P(A)=0.4, P(B)=0.3, independent. P(both)?",
    options: ["0.12", "0.7", "0.1", "0.07"],
    answer: "0.12",
    explanation: "",
    shortcut: "",
  },

  {
    id: 80,
    topic: "Probability",
    difficulty: "hard",
    type: "exam",
    question: "Class: 15 pass, 10 fail. P(pass or fail)?",
    options: ["15/25", "10/25", "25/25", "1/2"],
    answer: "25/25",
    explanation: "",
    shortcut: "",
  },
];